import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :the_band, TheBandWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :the_band, TheBandWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# O COOKIE DE SESSÃO SÓ VIAJA EM HTTPS — issue #1008, achado S15 da avaliação da US2 da 064.
#
# O `force_ssl` acima redireciona para HTTPS, mas o redirecionamento é a RESPOSTA à primeira
# requisição. Sem `Secure`, o navegador manda o cookie nessa primeira requisição em HTTP, antes
# de ser redirecionado, e o cookie passa em claro por quem estiver no caminho. É lido em tempo
# de compilação, como o `force_ssl`, porque as opções da sessão são um atributo do endpoint.
#
# Só aqui: em desenvolvimento e teste não há HTTPS, e com `Secure` o navegador não guardaria o
# cookie.
config :the_band, :cookie_de_sessao_seguro, true

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
